image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview  

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  #- init: echo 'init script' # runs during prebuild
  #- init: cd hello-axios && npm run serve
   - command:  json-server db.json &&
               cd hello-axios && npm run serve
  #  command: echo 'start script'

vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
